change: Migrate static analysis to Mago (#28)
* Setup mago

* Mago fix prefer-static-closure

* Mago fix braced-string-interpolatio

* Mago fix prefer-arrow-function

* Mago fix no-shorthand-ternary

* Mago config too-many-methods

* Mago fix literal-named-argument

* Mago fix readable-literal

* Mago fix no-else-clause

* Mago fix no-empty-comment

* Run mago lint in static-analysis workflow

* Mago fix formatting according to PER-CS

* Dry-run formatting in static-analysis workflow

* Intentionally trigger Mago issues

* Remove redudant check status step

* Re-add Mago report step to ensure the workflow fails in case of errors

* Cleanup static analysis output

* Streamline composer scripts

* Intentionally trigger Mago issues

* Fix intentional errors

* Enable phpunit linter integration

* Setup Mago analyse

* Run analyse:check in static-analysis workflow

* Remove php-cs-fixer and phpstan

* Fix analyzer issues

* Remove redundant HasErrorOnPath::resolveResponseUsing()

This was implementated to allow using the constraint on Laravel’s TestResponse object. However, there is no need for it. This can be solved by passing $response->json() instead of the TestResponse instance.

* Fix last few analyzer issues

* Fix tests

* Remove phpstan annotations

* Remove config files

* Preserve breaking member access chain

diff --git a/.github/workflows/static-analysis.yml b/.github/workflows/static-analysis.yml
--- a/.github/workflows/static-analysis.yml
+++ b/.github/workflows/static-analysis.yml
@@ -5,30 +5,53 @@ on:
     branches: ['main']
 
 jobs:
-  phpstan:
+  mago:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
       - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # https://github.com/shivammathur/setup-php/releases/tag/2.37.1
         with:
-          php-version: 8.4
+          php-version: 8.5
           extensions: -pdo_mysql, -mysqli
       - run: composer update --prefer-stable --prefer-dist --no-interaction
-      - run: composer phpstan
-
-  php-cs-fixer:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
-        with:
-          ref: ${{ github.head_ref }}
-      - name: 'Run PHP CS fixer'
-        uses: ./.github/actions/php-cs-fixer
-        with:
-          workspace: ${{ github.workspace }}
-          args: --config=.php-cs-fixer.dist.php --allow-risky=yes
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-      - name: 'Commit CS fixes'
-        uses: craftzing/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0
-        with:
-          commit_message: Fix code style violations
+      # Mago is installed through Composer, but the package is just a thin wrapper. By checking the version, we force
+      # the wrapper to download the binary before running actual checks in order not to pollute the check output...
+      - run: composer mago -- --version
+      - run: composer lint:check
+        id: lint
+        continue-on-error: true
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - run: composer format:check
+        id: format
+        continue-on-error: true
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - run: composer analyse:check
+        id: analyse
+        continue-on-error: true
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: 'Fail upon detected issues'
+        if: |
+          steps.lint.outcome == 'failure' || 
+          steps.format.outcome == 'failure' || 
+          steps.analyse.outcome == 'failure'
+        env:
+          LINT_OUTCOME: ${{ steps.lint.outcome }}
+          FORMAT_OUTCOME: ${{ steps.format.outcome }}
+          ANALYSE_OUTCOME: ${{ steps.analyse.outcome }}
+        run: |
+          if [ "$LINT_OUTCOME" == "failure" ]; then
+            echo "::error title=Lint::Linter detected issues."
+          fi
+          
+          if [ "$FORMAT_OUTCOME" == "failure" ]; then
+            echo "::error title=Format::Formatter detected files needing formatting."
+          fi
+          
+          if [ "$ANALYSE_OUTCOME" == "failure" ]; then
+            echo "::error title=Analyse::Analyzer detected issues."
+          fi
+          
+          exit 1
